# Generated by Django 3.1.7 on 2021-03-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='deviceaction',
            name='finished_at',
            field=models.DateField(null=True),
        ),
    ]
