# Generated by Django 3.1.7 on 2021-03-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_devicecron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecron',
            name='day_of_week',
            field=models.CharField(choices=[('0', 'Nerozhoduje'), ('1', 'Pondělí'), ('2', 'Úterý'), ('3', 'Středa'), ('4', 'Čtvrtek'), ('5', 'Pátek'), ('6', 'Sobota'), ('7', 'Neděle')], default='0', max_length=100),
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['device', 'option'], name='main_device_device__be3b20_idx'),
        ),
    ]
