# Generated by Django 3.1.7 on 2021-03-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210329_1135'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['device', 'option', 'created_at'], name='main_device_device__71ac9b_idx'),
        ),
    ]
