# Generated by Django 3.2.3 on 2021-08-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='outage_report_for',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
