# Generated by Django 3.2.3 on 2021-09-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_device_outage_report_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='outage_notification',
            field=models.BooleanField(default=True),
        ),
    ]
