# Generated by Django 3.2.3 on 2021-09-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_userdevice_outage_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='outage_notification',
            field=models.BooleanField(default=True),
        ),
    ]
