# Generated by Django 3.2.3 on 2021-10-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_client_outage_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='outage_notification',
            field=models.BooleanField(default=False),
        ),
    ]
