# Generated by Django 3.1.7 on 2021-03-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_client_outage_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
