# Generated by Django 3.1.7 on 2021-03-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_device_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
